dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = "dashboard"
urlpatterns = [
    path("", views.Dashboard.as_view(), name="dashboard"),
    path("overview/<int:id>", views.Dashboard.as_view()),
    path("overview/<int:id>/edit", views.Dashboard.as_view()),
    path("overview/<int:id>/ballot", views.Dashboard.as_view()),
    path("overview/<int:id>/voters", views.Dashboard.as_view()),
    path("overview/<int:id>/launch", views.Dashboard.as_view()),
    path("overview/<int:id>/results", views.Dashboard.as_view()),
    path("api/create-ballot/", views.CreateBallotAPIView.as_view()),
    path("api/list-ballots/", views.ListBallotsAPIView.as_view()),
    path("api/add-question/", views.AddQuestionAPIView.as_view()),
    path("api/add-option/", views.AddOptionAPIView.as_view()),
    path("api/view-ballot/<int:id>", views.ViewBallotAPIView.as_view()),
    path("api/delete-option/<int:id>", views.DeleteOptionAPIView.as_view()),
    path("api/delete-question/<int:id>", views.DeleteQuestionAPIView.as_view()),
    path("api/edit-option/<int:id>", views.EditOptionAPIView.as_view()),
    path("api/edit-question/<int:id>", views.EditQuestionAPIView.as_view()),
    path("api/edit-ballot/<int:id>", views.EditBallotAPIView.as_view()),
    path("api/delete-ballot/<int:id>", views.DeleteBallotAPIView.as_view()),
    path("api/add-voter/", views.AddVoterAPIView.as_view()),
    path("api/import-voters/", views.ImportVotersAPIView.as_view()),
    path("api/delete-voter/<int:id>", views.DeleteVoterAPIView.as_view()),
    path("api/delete-all-voters/<int:id>", views.DeleteAllVotersAPIView.as_view()),
    path("api/launch-ballot/<int:id>", views.LaunchAPIView.as_view()),
    path("api/vote/<int:id>", views.VoteAPIView.as_view()),
    path("api/login-voter/<int:id>", views.LoginVoterAPIView.as_view()),
    path("api/ballot-data/<int:id>", views.BallotDataAPIView.as_view()),
    path("api/close-ballot/<int:id>", views.CloseBallotAPIView.as_view()),
    path("api/logout/", views.LogoutAPIView.as_view()),
]

landing_page/urls.py
from re import template
from django.urls import path
from landing_page import views

app_name = "landing_page"
urlpatterns = [
    path("", views.landing_page, name="landing_page"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify_email'),
    path("forgot-password/", views.ResetUserPasswordView.as_view(), name="forgot_password"),
    path('reset-password/<uidb64>/<token>/', views.ResetUserPasswordConfirmView.as_view(), name='reset_password_confirm'),
]

landing_page/models.py
from django.db import models

# Create your models here.

landing_page/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm
from django import forms
from dashboard.models import User
from crispy_forms.helper import FormHelper

class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email","firstname", "lastname")

class ResetUserPasswordForm(PasswordResetForm):
    class Meta:
        model = User
        fields = "__all__"

class ResetUserPasswordConfirmForm(SetPasswordForm):
    class Meta:
        model = User
        fields = "__all__"

landing_page/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from dashboard.models import User
from django.urls import reverse
from landing_page import forms
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.contrib import messages

# Create your views here.
def landing_page(request):
    return render(request, "landing_page/landing_page.html")

class RegisterView(SuccessMessageMixin, CreateView):
    model = User
    template_name = "landing_page/register.html"
    form_class = forms.RegisterUserForm
    success_message = "We have sent an email to %(email)s. Please click the activation link included to verify your email address."

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
        cleaned_data,
        email=self.object.email,
    )

    def get_success_url(self):
        return reverse('login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user = form.save(commit = False)
        user.is_active = False #disables the just registered user account pending confirmation
        user.save()
        current_site = get_current_site(self.request) #Gets the current site
        subject = "Verify your email address"
        email_template_name = "landing_page/verify_email.html"
        context = {
        'domain':current_site.domain,
        'site_name': 'Poller',
        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
        "user": user,
        'token': default_token_generator.make_token(user),
        'protocol': 'http',
        }
        message = render_to_string(email_template_name, context)
        email = EmailMessage(subject, message, to=[email])
        email.send()
        return super().form_valid(form)


def verify_email(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except:
        user = None
    if user is not None:
        user.is_active = True
        user.save()
        messages.add_message(request, messages.INFO, f'Your email account {user.email} has been successfully verified.')
    else:
        messages.add_message(request, messages.INFO, 'Activation link is invalid.')
    login_url = reverse('login')
    return redirect(login_url)

class ResetUserPasswordView(SuccessMessageMixin, PasswordResetView):
    form_class = forms.ResetUserPasswordForm
    template_name = "landing_page/reset_password.html"
    email_template_name = 'landing_page/reset_password_email.html'
    subject_template_name = 'landing_page/reset_password_subject.txt'
    success_message = "We have received your request. If you have an account you should recieve and email with a link to reset your password shortly."

    def get_success_url(self):
        return reverse('landing_page:forgot_password')

class ResetUserPasswordConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    form_class = forms.ResetUserPasswordConfirmForm
    template_name = "landing_page/reset_password_confirm.html"
    success_message = 'Your password has been reset successfully.'

    def get_success_url(self):
        return reverse('login')

landing_page/templates/landing_page/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/form.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/ico" href="{% static 'landing_page/favicon.ico' %}"/>
    <title>Poller | Register</title>

</head>
<body>
    {% load crispy_forms_tags %}
    <main class="d-flex flex-column align-items-center justify-content-center mt-2 mb-3 p-2">
        <h2 class="mb-4 mt-2 fw-bold fs-2 text-info"><a href="{% url 'landing_page:landing_page' %}" class="text-decoration-none">POLLER</a></h2>
        <form method="post" class="form card w-100 needs-validation" novalidate oninput='password2.setCustomValidity(password.value != password2.value ? "Passwords do not match." : "")'>
            
            {% csrf_token %}
            <div class="card-body">
                <p class="fs-3 text-center mt-0">Sign up for <span class="fw-bold">free</span></p>
                {{ form | crispy }}
                <button class="btn btn-lg btn-success w-100 mb-3" type="submit">Continue</button>
                <p class="text-center">Already have an account? <a href="{% url 'login' %}" class="text-decoration-none text-info">Login</a></p>
            </div>
        </form>
    </main>

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top mb-0">
        <div class="col-md-4 d-flex align-items-center ms-5">
            <span class="mb-3 mb-md-0 text-muted d-flex flex-column">Copyright © 2022 Poller
                <span>Made by Michael Ikoko</span>
            </span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ms-4">
            <li class="ms-3 border-end border-secondary pe-3">
                <a class="text-muted" href="https://twitter.com/michael_ikoko?ref_src=twsrc%5Etfw" target="_blank">
                    <svg fill="#000000" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24px"
                        height="24px" class="footer-icon">
                        <path
                            d="M21.634,4.031c-0.815,0.385-2.202,1.107-2.899,1.245c-0.027,0.007-0.049,0.016-0.075,0.023 c-0.813-0.802-1.927-1.299-3.16-1.299c-2.485,0-4.5,2.015-4.5,4.5c0,0.131-0.011,0.372,0,0.5c-3.218,0-5.568-1.679-7.327-3.837 C3.438,4.873,3.188,5.024,3.136,5.23C3.019,5.696,2.979,6.475,2.979,7.031c0,1.401,1.095,2.777,2.8,3.63 c-0.314,0.081-0.66,0.139-1.02,0.139c-0.424,0-0.912-0.111-1.339-0.335c-0.158-0.083-0.499-0.06-0.398,0.344 c0.405,1.619,2.253,2.756,3.904,3.087c-0.375,0.221-1.175,0.176-1.543,0.176c-0.136,0-0.609-0.032-0.915-0.07 c-0.279-0.034-0.708,0.038-0.349,0.582c0.771,1.167,2.515,1.9,4.016,1.928c-1.382,1.084-3.642,1.48-5.807,1.48 c-0.438-0.01-0.416,0.489-0.063,0.674C3.862,19.504,6.478,20,8.347,20C15.777,20,20,14.337,20,8.999 c0-0.086-0.002-0.266-0.005-0.447C19.995,8.534,20,8.517,20,8.499c0-0.027-0.008-0.053-0.008-0.08 c-0.003-0.136-0.006-0.263-0.009-0.329c0.589-0.425,1.491-1.163,1.947-1.728c0.155-0.192,0.03-0.425-0.181-0.352 c-0.543,0.189-1.482,0.555-2.07,0.625c1.177-0.779,1.759-1.457,2.259-2.21C22.109,4.168,21.895,3.907,21.634,4.031z" />
                    </svg>
                </a>
            </li>

            <li class="ms-3 border-end border-secondary pe-3">
                <a class="text-muted" href="https://github.com/michaelikoko?tab=repositories" target="_blank">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="h-6 w-6 fill-slate-900 footer-icon">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                            d="M12 2C6.477 2 2 6.463 2 11.97c0 4.404 2.865 8.14 6.839 9.458.5.092.682-.216.682-.48 0-.236-.008-.864-.013-1.695-2.782.602-3.369-1.337-3.369-1.337-.454-1.151-1.11-1.458-1.11-1.458-.908-.618.069-.606.069-.606 1.003.07 1.531 1.027 1.531 1.027.892 1.524 2.341 1.084 2.91.828.092-.643.35-1.083.636-1.332-2.22-.251-4.555-1.107-4.555-4.927 0-1.088.39-1.979 1.029-2.675-.103-.252-.446-1.266.098-2.638 0 0 .84-.268 2.75 1.022A9.607 9.607 0 0 1 12 6.82c.85.004 1.705.114 2.504.336 1.909-1.29 2.747-1.022 2.747-1.022.546 1.372.202 2.386.1 2.638.64.696 1.028 1.587 1.028 2.675 0 3.83-2.339 4.673-4.566 4.92.359.307.678.915.678 1.846 0 1.332-.012 2.407-.012 2.734 0 .267.18.577.688.48 3.97-1.32 6.833-5.054 6.833-9.458C22 6.463 17.522 2 12 2Z">
                        </path>
                    </svg>
                </a>
            </li>

            <li class="ms-3 ">
                <a class="text-muted" href="mailto:michaelikoko.o@gmail.com">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
                        width="256" height="256" viewBox="0 0 256 256" xml:space="preserve" class="footer-icon">
                        <defs>
                        </defs>
                        <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;"
                            transform="translate(1.4065934065934016 1.4065934065934016) scale(2.81 2.81)">
                            <path
                                d="M 45 51.648 l 45 -27.845 v -6.422 c 0 -1.595 -1.293 -2.887 -2.887 -2.887 H 2.887 C 1.293 14.494 0 15.786 0 17.381 v 6.422 L 45 51.648 z"
                                style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;"
                                transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
                            <path
                                d="M 45.789 54.688 c -0.011 0.007 -0.023 0.008 -0.033 0.015 c -0.08 0.047 -0.166 0.08 -0.253 0.111 c -0.04 0.014 -0.077 0.035 -0.118 0.046 c -0.115 0.031 -0.233 0.045 -0.353 0.048 c -0.011 0 -0.021 0.004 -0.031 0.004 c 0 0 -0.001 0 -0.001 0 s -0.001 0 -0.001 0 c -0.011 0 -0.021 -0.004 -0.031 -0.004 c -0.119 -0.003 -0.238 -0.018 -0.353 -0.048 c -0.04 -0.011 -0.078 -0.032 -0.118 -0.046 c -0.087 -0.031 -0.172 -0.064 -0.253 -0.111 c -0.011 -0.006 -0.023 -0.008 -0.033 -0.015 L 0 27.331 v 45.289 c 0 1.594 1.293 2.887 2.887 2.887 h 84.226 c 1.594 0 2.887 -1.293 2.887 -2.887 V 27.331 L 45.789 54.688 z"
                                style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;"
                                transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
                        </g>
                    </svg>
                </a>
            </li>
        </ul>
    </footer>

    <script>
        const hintPassword1 = document.getElementById("hint_id_password1")
        hintPassword1.remove()
        const hintPassword2 = document.getElementById("hint_id_password2")
        hintPassword2.remove()
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

landing_page/templates/landing_page/reset_password.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"
        >
        <link rel="shortcut icon" type="image/ico" href="{% static 'landing_page/favicon.ico' %}"/>
        <title>Poller | Forgot Password</title>
        <link rel="stylesheet" href="{% static 'landing_page/form.css' %}">

    </head>

    <body>
        <main class="d-flex flex-column align-items-center justify-content-center mt-5 p-2">
            <h2 class="mb-4 mt-2 fw-bold fs-2 text-info"><a href="{% url 'landing_page:landing_page' %}"
                    class="text-decoration-none">POLLER</a>
            </h2>

            {% if messages %}
                <div class="form card w-100">
                    <div class="card-body">
                        <p class="fs-3 text-center mt-0">Reset Your Password</p>
                        <div class="bg-light text-start border border-dark border-opacity-25 rounded p-3">
                            {% for message in messages %}
                                <span>{{message}}</span>
                            {% endfor %}
                            <p class="text-start"><a href="{% url 'login' %}"
                                class="text-decoration-none text-info">&lt;&lt;Back to login</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% else %}
                <form method="post" class="form card w-100">
                    {% csrf_token %}
                    <div class="card-body">
                        <p class="fs-3 text-center mt-0">Reset Your Password</p>
                        <div class="mb-3">
                            <label for="emailForm" class="form-label fw-bold">Email address</label>
                            <input type="email" class="form-control" id="emailForm" required name="email"
                                placeholder="Enter Email Address">
                        </div>

                        <button class="btn btn-lg btn-success w-100 mb-3" type="submit">Send Reset Email</button>
                        <p class="text-center">Already have an account? <a href="{% url 'login' %}"
                                class="text-decoration-none text-info">Login</a></p>
                    </div>
                </form>
            {% endif %}
        </main>

        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top mb-0 fixed-bottom">
            <div class="col-md-4 d-flex align-items-center ms-5">
                <span class="mb-3 mb-md-0 text-muted d-flex flex-column">
                    Copyright © 2022 Poller
                    <span>Made by Michael Ikoko</span>
                </span>
            </div>
    
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-5 ms-4">
                <li class="ms-3 border-end border-secondary pe-3">
                    <a class="text-muted" href="https://twitter.com/michael_ikoko?ref_src=twsrc%5Etfw" target="_blank">
                        <svg fill="#000000" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24px"
                            height="24px" class="footer-icon"
                        >
                            <path
                                d="M21.634,4.031c-0.815,0.385-2.202,1.107-2.899,1.245c-0.027,0.007-0.049,0.016-0.075,0.023 c-0.813-0.802-1.927-1.299-3.16-1.299c-2.485,0-4.5,2.015-4.5,4.5c0,0.131-0.011,0.372,0,0.5c-3.218,0-5.568-1.679-7.327-3.837 C3.438,4.873,3.188,5.024,3.136,5.23C3.019,5.696,2.979,6.475,2.979,7.031c0,1.401,1.095,2.777,2.8,3.63 c-0.314,0.081-0.66,0.139-1.02,0.139c-0.424,0-0.912-0.111-1.339-0.335c-0.158-0.083-0.499-0.06-0.398,0.344 c0.405,1.619,2.253,2.756,3.904,3.087c-0.375,0.221-1.175,0.176-1.543,0.176c-0.136,0-0.609-0.032-0.915-0.07 c-0.279-0.034-0.708,0.038-0.349,0.582c0.771,1.167,2.515,1.9,4.016,1.928c-1.382,1.084-3.642,1.48-5.807,1.48 c-0.438-0.01-0.416,0.489-0.063,0.674C3.862,19.504,6.478,20,8.347,20C15.777,20,20,14.337,20,8.999 c0-0.086-0.002-0.266-0.005-0.447C19.995,8.534,20,8.517,20,8.499c0-0.027-0.008-0.053-0.008-0.08 c-0.003-0.136-0.006-0.263-0.009-0.329c0.589-0.425,1.491-1.163,1.947-1.728c0.155-0.192,0.03-0.425-0.181-0.352 c-0.543,0.189-1.482,0.555-2.07,0.625c1.177-0.779,1.759-1.457,2.259-2.21C22.109,4.168,21.895,3.907,21.634,4.031z" />
                        </svg>
                    </a>
                </li>

                <li class="ms-3 border-end border-secondary pe-3">
                    <a class="text-muted" href="https://github.com/michaelikoko?tab=repositories" target="_blank">
                        <svg viewBox="0 0 24 24" aria-hidden="true" class="h-6 w-6 fill-slate-900 footer-icon">
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                d="M12 2C6.477 2 2 6.463 2 11.97c0 4.404 2.865 8.14 6.839 9.458.5.092.682-.216.682-.48 0-.236-.008-.864-.013-1.695-2.782.602-3.369-1.337-3.369-1.337-.454-1.151-1.11-1.458-1.11-1.458-.908-.618.069-.606.069-.606 1.003.07 1.531 1.027 1.531 1.027.892 1.524 2.341 1.084 2.91.828.092-.643.35-1.083.636-1.332-2.22-.251-4.555-1.107-4.555-4.927 0-1.088.39-1.979 1.029-2.675-.103-.252-.446-1.266.098-2.638 0 0 .84-.268 2.75 1.022A9.607 9.607 0 0 1 12 6.82c.85.004 1.705.114 2.504.336 1.909-1.29 2.747-1.022 2.747-1.022.546 1.372.202 2.386.1 2.638.64.696 1.028 1.587 1.028 2.675 0 3.83-2.339 4.673-4.566 4.92.359.307.678.915.678 1.846 0 1.332-.012 2.407-.012 2.734 0 .267.18.577.688.48 3.97-1.32 6.833-5.054 6.833-9.458C22 6.463 17.522 2 12 2Z">
                            </path>
                        </svg>
                    </a>
                </li>
    
                <li class="ms-3 ">
                    <a class="text-muted" href="mailto:michaelikoko.o@gmail.com">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
                            width="256" height="256" viewBox="0 0 256 256" xml:space="preserve" class="footer-icon"
                        >
                            <defs>
                            </defs>
                            <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;"
                                transform="translate(1.4065934065934016 1.4065934065934016) scale(2.81 2.81)"
                            >
                                <path
                                    d="M 45 51.648 l 45 -27.845 v -6.422 c 0 -1.595 -1.293 -2.887 -2.887 -2.887 H 2.887 C 1.293 14.494 0 15.786 0 17.381 v 6.422 L 45 51.648 z"
                                    style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;"
                                    transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
                                <path
                                    d="M 45.789 54.688 c -0.011 0.007 -0.023 0.008 -0.033 0.015 c -0.08 0.047 -0.166 0.08 -0.253 0.111 c -0.04 0.014 -0.077 0.035 -0.118 0.046 c -0.115 0.031 -0.233 0.045 -0.353 0.048 c -0.011 0 -0.021 0.004 -0.031 0.004 c 0 0 -0.001 0 -0.001 0 s -0.001 0 -0.001 0 c -0.011 0 -0.021 -0.004 -0.031 -0.004 c -0.119 -0.003 -0.238 -0.018 -0.353 -0.048 c -0.04 -0.011 -0.078 -0.032 -0.118 -0.046 c -0.087 -0.031 -0.172 -0.064 -0.253 -0.111 c -0.011 -0.006 -0.023 -0.008 -0.033 -0.015 L 0 27.331 v 45.289 c 0 1.594 1.293 2.887 2.887 2.887 h 84.226 c 1.594 0 2.887 -1.293 2.887 -2.887 V 27.331 L 45.789 54.688 z"
                                    style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;"
                                    transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
                            </g>
                        </svg>
                    </a>
                </li>
            </ul>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous">
        </script>
    </body>
</html>

landing_page/templates/landing_page/reset_password_email.html
Hello,

We received a request to reset the password for your account for this email address: {{email}}. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'landing_page:reset_password_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
Poller


landing_page/templates/landing_page/verify_email.html
{% autoescape off %}

Hi {{user.firstname}}. Kindly click on the link below to verify your email address:

{{ protocol }}://{{ domain }}{% url 'landing_page:verify_email' uidb64=uid token=token %}

If you did not make this request, you can simply ignore this email.

Sincerely,
Poller

{% endautoescape %}
